name 'winlogbeats'
maintainer 'Dan Webb'
maintainer_email 'dan.webb@damacus.io'
license 'Apache-2.0'
description 'Installs Winlogbeat Agent '
issues_url 'https://github.com/damacus/chef-winlogbeats/issues'
source_url 'https://github.com/damacus/chef-winlogbeats'
version '0.0.5'
chef_version '>= 15.0'

depends 'windows'
